### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by hngocuyen** [cintagram/pyi-auto-decompile#1]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\output\pyi-auto-decompile\main.py", line 36, in <module>
    with open(os.path.join(extractpath, "re.pyc"), "rb") as fe:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\Desktop\\output\\pyi-auto-decompile\\exe_extracted\\base_library_ex\\re.pyc'

**Comment by cintagram** [comment]
Check if your exe file is pyinstaller exe.

or send me your exe file so that i can analyze the file and patch codes
